import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Uplevel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-900 h-screen'>
        <nav className="bg-slate-900 shadow">
          <div className="container flex items-center justify-center p-6 mx-auto capitalize text-gray-300">
            <Link href="./pages/index.html" className="transition-colors duration-300 transform text-gray-200 border-b-2 border-green-500 mx-1.5 sm:mx-6">home</Link>
            <Link href="./quiz.html" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Pelajaran</Link>
            <Link href="./tutor.html" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Tanya</Link>
            <Link href="./forum.html" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Forum</Link>
            <Link href="./premium.html" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Premium</Link>
            <Link href="./login.html" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Login</Link>
            <Link href="./register.html" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Register</Link>
          </div>
        </nav>
        <p>Hello world</p>
      </main>
    </div>
  )
}
