import Head from 'next/head'
import Link from 'next/link'

export default function Login() {
  return (
    <div>
      <Head>
        <title>Uplevel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-900 h-screen'>
        <nav className="bg-slate-900 shadow">
          <div className="container flex items-center justify-center p-6 capitalize text-gray-300">
            <Link href="/" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Home</Link>
            <Link href="/premium" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Premium</Link>
            <Link href="/login" className="transition-colors duration-300 transform text-gray-200 border-b-2 border-green-500 mx-1.5 sm:mx-6">Login</Link>
            <Link href="/register" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Register</Link>
          </div>
        </nav>
        <div className="mx-auto max-w-screen-xl px-4 py-20 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-lg">
                <h1 className="text-center text-3xl font-semibold text-slate-50 sm:text-3xl">
                    Welcome to <span className="text-green-500">Uplevel</span>
                </h1>

                <p className="mx-auto mt-4 max-w-md text-center text-gray-500">

                </p>

                <form action="" className="bg-slate-800 mt-6 mb-0 space-y-4 rounded-lg p-8 mt-10 shadow-2xl">
                    <p className="text-lg font-medium text-gray-200">Sign in to your account</p>

                    <div>
                    <label htmlFor="email" className="text-gray-200 text-sm font-medium">Email</label>

                    <div className="relative mt-1">
                        <input type="email" id="email" className="w-full rounded-lg border-gray-200 bg-slate-200 p-4 pr-12 text-sm shadow-sm"
                        placeholder="Enter email" />

                        <span className="absolute inset-y-0 right-4 inline-flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
                        </svg>
                        </span>
                    </div>
                    </div>

                    <div>
                    <label htmlFor="password" className="text-gray-200 text-sm font-medium">Password</label>

                    <div className="relative mt-1">
                        <input type="password" id="password" className="w-full rounded-lg border-gray-200 bg-slate-200 p-4 pr-12 text-sm shadow-sm"
                        placeholder="Enter password" />

                        <span className="absolute inset-y-0 right-4 inline-flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                        </span>
                    </div>
                    </div>

                    <button type="submit" className="block w-full rounded-lg bg-green-500 px-5 py-3 text-sm font-bold text-white">
                    Sign in
                    </button>

                </form>
            </div>
        </div>       
      </main>
    </div>
  )
}
