import Head from 'next/head'
import Link from 'next/link'

export default function Premium() {
    return (
      <div>
        <Head>
          <title>Uplevel</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='bg-slate-900 h-screen'>
          <nav className="bg-slate-900 shadow">
            <div className="container flex items-center justify-center p-6 capitalize text-gray-300">
              <Link href="/" className="relative border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Home</Link>
              <Link href="/premium" className="transition-colors duration-300 transform text-gray-200 border-b-2 border-green-500 mx-1.5 sm:mx-6">Premium</Link>
              <Link href="/login" className="relative border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Login</Link>
              <Link href="/register" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Register</Link>
            </div>
          </nav>
          <div className="relative w-full h-full">
            <div className="absolute hidden w-full bg-slate-900 lg:block h-full"></div>
            <div className="relative px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
                <div className="max-w-xl mb-10 md:mx-auto sm:text-center lg:max-w-2xl md:mb-12">
                    <h2
                    className="max-w-lg mb-6 font-sans text-3xl font-semibold leading-none tracking-tight text-white sm:text-3xl md:mx-auto">
                    <span className="relative inline-block">

                        <span className="relative text-green-500">Level Up</span>
                    </span>
                    &nbsp;to Premium
                    </h2>
                    <p className="text-base text-white md:text-lg">
                    Upgrade akun-mu ke premium untuk mendapatkan benefit tambahan
                    </p>
                </div>
                <div className="grid max-w-screen-md gap-10 md:grid-cols-2 sm:mx-auto">
                    <div>
                    <div className="p-8 bg-slate-800 rounded">
                        <div className="mb-4 text-center">
                        <p className="text-xl font-medium tracking-wide text-white">
                            Biasa
                        </p>
                        <div className="flex items-center justify-center">
                            <p className="mr-2 text-4xl font-semibold text-white lg:text-3xl">
                            Rp 0
                            </p>
                            <p className="text-lg text-gray-400">/ bulan</p>
                        </div>
                        </div>
                        <ul className="mb-8 space-y-2">
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="#22C55E" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="#22C55E"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Materi, Video, Quiz Gratis</p>
                        </li>
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="#ff0000" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="#ff0000"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Pembahasan Quiz</p>
                        </li>
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="red" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="red"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Chat Tentor</p>
                        </li>
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="red" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="red"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Diskusi pada forum</p>
                        </li>
                        </ul>
                        <button type="submit"
                        className="inline-flex items-center justify-center w-full h-12 px-6 font-medium tracking-wide text-white transition duration-200 rounded shadow-md bg-slate-700 hover:bg-slate-500 focus:shadow-outline focus:outline-none">
                        Masuk
                        </button>
                    </div>
                    <div className="w-11/12 h-2 mx-auto bg-gray-900 rounded-b opacity-75"></div>
                    <div className="w-10/12 h-2 mx-auto bg-gray-900 rounded-b opacity-50"></div>
                    <div className="w-9/12 h-2 mx-auto bg-gray-900 rounded-b opacity-25"></div>
                    </div>
                    <div>
                    <div className="p-8 bg-slate-800 rounded">
                        <div className="mb-4 text-center">
                        <p className="text-xl font-medium tracking-wide text-white">Premium</p>
                        <div className="flex items-center justify-center">
                            <p className="mr-2 text-5xl font-semibold text-white lg:text-3xl">
                            Rp 150.000
                            </p>
                            <p className="text-lg text-gray-400">/ bulan</p>
                        </div>
                        </div>
                        <ul className="mb-8 space-y-2">
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="#22C55E" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="#22C55E"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Materi, Video, Quiz, Premium</p>
                        </li>
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="#22C55E" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="#22C55E"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Pembahasan Quiz</p>
                        </li>
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="#22C55E" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="#22C55E"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Chat Tentor</p>
                        </li>
                        <li className="flex items-center">
                            <div className="mr-3">
                            <svg className="w-4 h-4 text-teal-accent-400" viewBox="0 0 24 24" stroke-linecap="round" stroke-width="2">
                                <polyline fill="none" stroke="#22C55E" points="6,12 10,16 18,8"></polyline>
                                <circle cx="12" cy="12" fill="none" r="11" stroke="#22C55E"></circle>
                            </svg>
                            </div>
                            <p className="font-medium text-gray-300">Diskusi Forum</p>
                        </li>
                        </ul>
                        <button type="submit"
                        className="inline-flex items-center justify-center w-full h-12 px-6 font-semibold tracking-wide text-white transition duration-200 rounded shadow-md bg-slate-700 hover:bg-green-500 focus:shadow-outline focus:outline-none">
                        Beli
                        </button>
                    </div>
                    <div className="w-11/12 h-2 mx-auto bg-gray-900 rounded-b opacity-75"></div>
                    <div className="w-10/12 h-2 mx-auto bg-gray-900 rounded-b opacity-50"></div>
                    <div className="w-9/12 h-2 mx-auto bg-gray-900 rounded-b opacity-25"></div>
                    </div>
                </div>
            </div>
        </div>
        </main>
      </div>
    )
  }