import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Uplevel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-900 h-screen'>
        <nav className="bg-slate-900 shadow">
          <div className="container flex items-center justify-center p-6 capitalize text-gray-300">
            <Link href="/" className="relative border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Home</Link>
            <Link href="/premium" className="border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Premium</Link>
            <Link href="/login" className="relative border-b-2 border-transparent transition-colors duration-300 transform hover:text-gray-200 hover:border-green-500 mx-1.5 sm:mx-6">Login</Link>
            <Link href="/register" className="transition-colors duration-300 transform text-gray-200 border-b-2 border-green-500 mx-1.5 sm:mx-6">Register</Link>
          </div>
        </nav>
        <section className="bg-slate-900">
            <div className="flex justify-center min-h-screen">

                <div className="flex w-full max-w-3xl p-9 mx-auto lg:px-12 lg:w-2/5">
                    <div className="w-full">
                        <h1 className="mt-11 text-center text-3xl font-semibold text-white capitalize dark:text-white">
                            Start your <span className="text-green-500">adventure</span>
                        </h1>

                        <form className="bg-slate-800 p-8 grid grid-cols-1 gap-6 mt-10 rounded-lg md:grid-cols-2">
                            <div>
                                <label className="block mb-2 text-sm text-gray-600 dark:text-gray-200">First Name</label>
                                <input type="text" placeholder="John"
                                    className="w-full rounded-lg border-gray-200 bg-slate-200 p-3 pr-12 text-sm shadow-sm" />
                            </div>

                            <div>
                                <label className="block mb-2 text-sm text-gray-600 dark:text-gray-200">Last name</label>
                                <input type="text" placeholder="Snow"
                                    className="w-full rounded-lg border-gray-200 bg-slate-200 px-5 py-3 text-sm shadow-smName" />
                            </div>

                            <div>
                                <label className="block mb-2 text-sm text-gray-600 dark:text-gray-200">Phone number</label>
                                <input type="text" placeholder="XXX-XX-XXXX-XXX"
                                    className="w-full rounded-lg border-gray-200 bg-slate-200 px-5 py-3 text-sm shadow-smName" />
                            </div>

                            <div>
                                <label className="block mb-2 text-sm text-gray-600 dark:text-gray-200">Email address</label>
                                <input type="email" placeholder="johnsnow@example.com"
                                    className="w-full rounded-lg border-gray-200 bg-slate-200 px-5 py-3 text-sm shadow-smName" />
                            </div>

                            <div>
                                <label className="block mb-2 text-sm text-gray-600 dark:text-gray-200">Password</label>
                                <input type="password" placeholder="Enter your password"
                                    className="w-full rounded-lg border-gray-200 bg-slate-200 px-5 py-3 text-sm shadow-smName" />
                            </div>

                            <div>
                                <label className="block mb-2 text-sm text-gray-600 dark:text-gray-200">Confirm password</label>
                                <input type="password" placeholder="Enter your password"
                                    className="w-full rounded-lg border-gray-200 bg-slate-200 px-5 py-3 text-sm shadow-smName" />
                            </div>

                            <button
                                className="flex items-center justify-between w-full px-6 py-3 text-sm tracking-wide text-white capitalize transition-colors duration-300 transform bg-green-500 text-bold rounded-md hover:bg-green-300 focus:outline-none focus:ring focus:ring-green-300 focus:ring-opacity-50">
                                <span>Sign Up </span>

                                <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 rtl:-scale-x-100" viewBox="0 0 20 20"
                                    fill="currentColor">
                                    <path fill-rule="evenodd"
                                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                        clip-rule="evenodd" />
                                </svg>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
      </main>
    </div>
  )
}
